return {
    -- Vehicle Code Violations (VC) - Low
    {
        id = 1,
        label = '5-9 MPH Over Speed Limit',
        description = 'Driving 5-9 MPH over posted speed limit, endangering safety of persons or property.',
        fine = 250,
        months = 0,
        level = 'low',
    },
    {
        id = 2,
        label = '10-19 MPH Over Speed Limit',
        description = 'Driving 10-19 MPH over posted speed limit, endangering safety of persons or property.',
        fine = 500,
        months = 0,
        level = 'low',
    },
    {
        id = 3,
        label = '20-29 MPH Over Speed Limit',
        description = 'Driving 20-29 MPH over posted speed limit, endangering safety of persons or property.',
        fine = 750,
        months = 0,
        level = 'low',
    },
    {
        id = 4,
        label = '30-39 MPH Over Speed Limit',
        description = 'Driving 30-39 MPH over posted speed limit, endangering safety of persons or property.',
        fine = 1000,
        months = 0,
        level = 'low',
    },
    {
        id = 5,
        label = '40-50 MPH Over Speed Limit',
        description = 'Driving 40-50 MPH over posted speed limit, endangering safety of persons or property.',
        fine = 1500,
        months = 0,
        level = 'low',
    },
    {
        id = 6,
        label = 'Careless Driving',
        description = 'Operating a vehicle with careless disregard for safety, including speeding, texting, or illegal lane changes.',
        fine = 1000,
        months = 1,
        level = 'low',
    },
    {
        id = 7,
        label = 'Failure to Maintain Lane',
        description = 'Not maintaining vehicle within a single lane or changing lanes unsafely.',
        fine = 250,
        months = 0,
        level = 'low',
    },
    {
        id = 8,
        label = 'Failure to Yield',
        description = 'Not yielding right-of-way when required during turns or merging.',
        fine = 250,
        months = 0,
        level = 'low',
    },
    {
        id = 9,
        label = 'Following Too Closely',
        description = 'Following another vehicle more closely than reasonable and prudent.',
        fine = 250,
        months = 0,
        level = 'low',
    },
    {
        id = 10,
        label = 'No Headlights/Tail-Lights',
        description = 'Operating vehicle without proper headlights or tail-lights during required times.',
        fine = 150,
        months = 0,
        level = 'low',
    },
    {
        id = 11,
        label = 'Illegal Parking',
        description = 'Parking in prohibited areas or blocking traffic/sidewalks.',
        fine = 200,
        months = 0,
        level = 'low',
    },
    {
        id = 12,
        label = 'Improper Turn',
        description = 'Making unsafe or illegal turns without proper signaling or right-of-way.',
        fine = 250,
        months = 0,
        level = 'low',
    },
    {
        id = 13,
        label = 'Driving Wrong Way',
        description = 'Operating vehicle against designated traffic flow direction.',
        fine = 500,
        months = 0,
        level = 'low',
    },
    {
        id = 14,
        label = 'Failure to Obey Traffic Device',
        description = 'Disregarding traffic signals, signs, or markings.',
        fine = 500,
        months = 0,
        level = 'low',
    },
    {
        id = 15,
        label = 'Impeding Traffic',
        description = 'Driving at speeds that block normal traffic flow or stopping unnecessarily on roadway.',
        fine = 300,
        months = 0,
        level = 'low',
    },
    {
        id = 16,
        label = 'Unsafe Vehicle',
        description = 'Operating a vehicle in an unsafe condition that presents immediate safety hazard.',
        fine = 500,
        months = 0,
        level = 'low',
    },
    {
        id = 17,
        label = 'Illegal Passing',
        description = 'Unsafe passing or overtaking other vehicles.',
        fine = 400,
        months = 0,
        level = 'low',
    },
    -- Misdemeanors (MC) - Medium
    {
        id = 18,
        label = 'Abuse of 911',
        description = 'Using 911 emergency system for non-emergency purposes.',
        fine = 1000,
        months = 3,
        level = 'medium',
    },
    {
        id = 19,
        label = 'Assault',
        description = 'Unlawful attempt to commit violent injury on another person.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 20,
        label = 'Battery',
        description = 'Willful and unlawful use of force or violence upon another person.',
        fine = 2500,
        months = 8,
        level = 'medium',
    },
    {
        id = 21,
        label = 'Burglary Tools',
        description = 'Possession of tools intended for burglary or breaking and entering.',
        fine = 1500,
        months = 6,
        level = 'medium',
    },
    {
        id = 22,
        label = 'Destruction of Property',
        description = 'Malicious damage or destruction of property belonging to another.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 23,
        label = 'Disorderly Conduct',
        description = 'Engaging in lewd or disruptive behavior in public, including public intoxication.',
        fine = 1000,
        months = 3,
        level = 'medium',
    },
    {
        id = 24,
        label = 'Disturbing the Peace',
        description = 'Creating unreasonable noise or engaging in fighting in public places.',
        fine = 1000,
        months = 3,
        level = 'medium',
    },
    {
        id = 25,
        label = 'Drug Possession',
        description = 'Possession of controlled substances beyond legal limits.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 26,
        label = 'Failure to Identify',
        description = 'Providing false identification or refusing to identify to law enforcement.',
        fine = 1500,
        months = 3,
        level = 'medium',
    },
    {
        id = 27,
        label = 'Illegal Gaming',
        description = 'Operating or participating in unauthorized gambling activities.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 28,
        label = 'Indecent Exposure',
        description = 'Willfully exposing private parts in public or in view of others.',
        fine = 1500,
        months = 3,
        level = 'medium',
    },
    {
        id = 29,
        label = 'Loitering',
        description = 'Remaining in an area without lawful purpose or permission.',
        fine = 500,
        months = 1,
        level = 'medium',
    },
    {
        id = 30,
        label = 'Making False Report',
        description = 'Knowingly making false statements to law enforcement.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 31,
        label = 'Obstruction',
        description = 'Willfully resisting, delaying, or obstructing law enforcement or emergency personnel.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 32,
        label = 'Petty Theft',
        description = 'Theft of property valued under $950.',
        fine = 1000,
        months = 3,
        level = 'medium',
    },
    -- Felonies (FC) - High
    {
        id = 33,
        label = 'Armed Robbery',
        description = 'Taking property from another person using force or fear while armed.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 34,
        label = 'Attempted Murder',
        description = 'Failed attempt to unlawfully kill another person with malice aforethought.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 35,
        label = 'Bank Robbery',
        description = 'Armed theft from a financial institution.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 36,
        label = 'Kidnapping',
        description = 'Unlawful detention and transportation of a person against their will.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 37,
        label = 'Murder',
        description = 'Unlawful killing of another person with malice aforethought.',
        fine = 25000,
        months = 60,
        level = 'high',
    },
    {
        id = 38,
        label = 'Drug Manufacturing',
        description = 'Production of illegal controlled substances or exceeding legal cultivation limits.',
        fine = 12000,
        months = 30,
        level = 'high',
    },
    {
        id = 39,
        label = 'Drug Trafficking',
        description = 'Distribution or intent to distribute controlled substances.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 40,
        label = 'Extortion',
        description = 'Obtaining property or services through force, threats, or coercion.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 41,
        label = 'Grand Theft',
        description = 'Theft of property valued over $950 or specified items regardless of value.',
        fine = 8000,
        months = 18,
        level = 'high',
    },
    {
        id = 42,
        label = 'Weapon Trafficking',
        description = 'Unlawful sale or distribution of firearms or prohibited weapons.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 43,
        label = 'Attempted Murder of LEO',
        description = 'Attempted murder of a law enforcement officer in the line of duty.',
        fine = 25000,
        months = 60,
        level = 'high',
    },
    {
        id = 44,
        label = 'Burglary of Government Facility',
        description = 'Breaking and entering into government property with intent to commit crime.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 45,
        label = 'Carjacking',
        description = 'Taking a motor vehicle from another person by force or fear.',
        fine = 12000,
        months = 30,
        level = 'high',
    },
    {
        id = 46,
        label = 'Possession of Automatic Weapon',
        description = 'Unlawful possession of automatic firearms.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 47,
        label = 'Possession of Firearm During Felony',
        description = 'Possession of firearm while committing a felony offense.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 48,
        label = 'Escape from Custody',
        description = 'Escaping or attempting to escape from lawful custody.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 49,
        label = 'Felon in Possession of Firearm',
        description = 'Possession of firearm by person convicted of felony.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 50,
        label = 'Terroristic Threats',
        description = 'Threats to commit violence or cause bodily injury resulting in terror.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    -- Hunting Code Violations (HC) - Other
    {
        id = 51,
        label = 'Hunting in Restricted Areas',
        description = 'Hunting outside designated hunting zones.',
        fine = 1000,
        months = 0,
        level = 'other',
    },
    {
        id = 52,
        label = 'Unlicensed Hunting',
        description = 'Hunting without proper license or permits.',
        fine = 1000,
        months = 0,
        level = 'other',
    },
    {
        id = 53,
        label = 'Animal Cruelty',
        description = 'Causing unnecessary harm to animals during hunting or otherwise.',
        fine = 2500,
        months = 6,
        level = 'other',
    },
    {
        id = 54,
        label = 'Non-Hunting Weapon Use',
        description = 'Using non-approved weapons for hunting (only shotguns permitted).',
        fine = 2000,
        months = 6,
        level = 'other',
    },
    {
        id = 55,
        label = 'Night Hunting',
        description = 'Hunting outside permitted hours (dusk to dawn).',
        fine = 1000,
        months = 0,
        level = 'other',
    },
    {
        id = 56,
        label = 'Poaching',
        description = 'Illegal possession of endangered species parts (cougar, sharks, turtles).',
        fine = 10000,
        months = 24,
        level = 'other',
    },
    {
        id = 57,
        label = 'Hunting From Vehicle',
        description = 'Hunting from inside or on a vehicle.',
        fine = 5000,
        months = 12,
        level = 'other',
    },
    {
        id = 58,
        label = 'Hunting Near Roadway',
        description = 'Hunting within 100 yards of a roadway.',
        fine = 2000,
        months = 6,
        level = 'other',
    },
    -- Additional Misdemeanors
    {
        id = 59,
        label = 'Possession of Stolen Property',
        description = 'Knowingly possessing property obtained through theft.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 60,
        label = 'Prostitution',
        description = 'Engaging in or soliciting sexual services for compensation.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    -- Additional Felonies
    {
        id = 61,
        label = 'Aggravated Assault',
        description = 'Assault causing serious bodily injury or with deadly weapon.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 62,
        label = 'Aggravated Battery',
        description = 'Battery causing serious bodily injury.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 63,
        label = 'Arson',
        description = 'Willfully and maliciously setting fire to property.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 64,
        label = 'Police Corruption',
        description = 'Law enforcement officer abusing position for personal gain.',
        fine = 25000,
        months = 60,
        level = 'high',
    },
    {
        id = 65,
        label = 'Hit and Run',
        description = 'Leaving scene of accident without providing information.',
        fine = 5000,
        months = 12,
        level = 'medium',
    },
    {
        id = 66,
        label = 'Unlawful Assembly',
        description = 'Remaining at scene of riot/unlawful assembly after dispersal warning.',
        fine = 1500,
        months = 3,
        level = 'medium',
    },
    {
        id = 67,
        label = 'Tampering with Evidence',
        description = 'Altering, destroying, or concealing evidence in investigation.',
        fine = 2500,
        months = 6,
        level = 'medium',
    },
    {
        id = 68,
        label = 'Resisting Arrest',
        description = 'Willfully resisting, delaying, or obstructing arrest.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 69,
        label = 'Public Intoxication',
        description = 'Being under influence of substances in public, unable to care for safety.',
        fine = 500,
        months = 1,
        level = 'medium',
    },
    {
        id = 70,
        label = 'Possession with Intent',
        description = 'Possession of controlled substances with intent to distribute.',
        fine = 3000,
        months = 8,
        level = 'medium',
    },
    {
        id = 71,
        label = 'Open Alcohol Container',
        description = 'Possessing open alcoholic beverage container in public space.',
        fine = 500,
        months = 0,
        level = 'medium',
    },
    {
        id = 72,
        label = 'Impersonating LEO',
        description = 'Falsely representing oneself as law enforcement officer.',
        fine = 2500,
        months = 6,
        level = 'medium',
    },
    {
        id = 73,
        label = 'Theft by Receiving',
        description = 'Receiving or concealing property known to be stolen.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 74,
        label = 'Vehicular Manslaughter',
        description = 'Causing death through negligent/unlawful operation of vehicle.',
        fine = 5000,
        months = 12,
        level = 'medium',
    },
    {
        id = 75,
        label = 'Violating Court Order',
        description = 'Knowingly violating terms of court order or protective order.',
        fine = 2500,
        months = 6,
        level = 'medium',
    },
    {
        id = 76,
        label = 'Aiding and Abetting',
        description = 'Knowingly assisting another in committing or escaping from felony.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 77,
        label = 'Aggravated Robbery',
        description = 'Robbery involving deadly weapon or serious injury.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 78,
        label = 'Battery on LEO',
        description = 'Battery committed against law enforcement officer.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 79,
        label = 'Brandishing Firearm',
        description = 'Drawing or exhibiting firearm in threatening manner.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 80,
        label = 'Burglary',
        description = 'Entering building with intent to commit theft or felony.',
        fine = 8000,
        months = 18,
        level = 'high',
    },
    {
        id = 81,
        label = 'Bribery',
        description = 'Offering or accepting something of value to influence official action.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 82,
        label = 'Embezzlement',
        description = 'Fraudulent conversion of property by person in possession.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 83,
        label = 'Forgery',
        description = 'Creating or altering documents with intent to defraud.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 84,
        label = 'Fraud',
        description = 'Deception for financial or personal gain.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 85,
        label = 'Manslaughter',
        description = 'Unlawful killing without malice aforethought.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 86,
        label = 'Mass Murder',
        description = 'Murder of multiple victims in a single incident.',
        fine = 25000,
        months = 60,
        level = 'high',
    },
    {
        id = 87,
        label = 'Pandering',
        description = 'Procuring or encouraging persons for prostitution.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 88,
        label = 'Possession while Trafficking',
        description = 'Possession of firearm while engaged in drug trafficking.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 89,
        label = 'Possession of Electronic Control Device',
        description = 'Unlawful possession of taser or similar device.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 90,
        label = 'Reckless Driving',
        description = 'Operating vehicle at 50+ MPH over limit or with extreme disregard for safety.',
        fine = 5000,
        months = 12,
        level = 'medium',
    },
    {
        id = 91,
        label = 'Reckless Evading',
        description = 'Failing to stop for law enforcement with dangerous disregard for safety.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 92,
        label = 'Hit and Run with Injury',
        description = 'Leaving scene of accident involving injury without providing information.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 93,
        label = 'Brandishing Weapon',
        description = 'Drawing or exhibiting deadly weapon other than firearm in threatening manner.',
        fine = 5000,
        months = 12,
        level = 'high',
    },
    {
        id = 94,
        label = 'Rioting',
        description = 'Participating in violent public disturbance with multiple participants.',
        fine = 2500,
        months = 6,
        level = 'medium',
    },
    {
        id = 95,
        label = 'Trespassing',
        description = 'Entering/remaining on property without permission or legal right.',
        fine = 1000,
        months = 3,
        level = 'medium',
    },
    {
        id = 96,
        label = 'Vandalism',
        description = 'Malicious defacement, damage, or destruction of property.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 97,
        label = 'Driving While Intoxicated',
        description = 'Operating vehicle under influence of alcohol or drugs.',
        fine = 2500,
        months = 6,
        level = 'low',
    },
    {
        id = 98,
        label = 'Illegal Street Racing',
        description = 'Participating in unauthorized speed contest on public roads.',
        fine = 5000,
        months = 12,
        level = 'low',
    },
    {
        id = 99,
        label = 'Carry Concealed Weapon',
        description = 'Carrying concealed firearm without proper permit.',
        fine = 2500,
        months = 6,
        level = 'medium',
    },
    {
        id = 100,
        label = 'Drug Paraphernalia',
        description = 'Possession of equipment used for consuming controlled substances.',
        fine = 1000,
        months = 3,
        level = 'medium',
    },
    {
        id = 101,
        label = 'Cyberstalking',
        description = 'Using electronic communications to harass or intimidate.',
        fine = 2500,
        months = 6,
        level = 'medium',
    },
    {
        id = 102,
        label = 'Identity Theft',
        description = 'Unlawful use of personal identifying information of another person.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 103,
        label = 'Cryptocurrency Fraud',
        description = 'Using cryptocurrency for fraudulent transactions or money laundering.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 104,
        label = 'Drone Violations',
        description = 'Unauthorized use of drones in restricted areas or for criminal purposes.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 105,
        label = 'Electronic Harassment',
        description = 'Using electronic devices to threaten, harass, or intimidate.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 106,
        label = 'Data Theft',
        description = 'Unauthorized access and theft of digital information or data.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 107,
        label = 'Illegal Surveillance',
        description = 'Unauthorized monitoring or recording of individuals without consent.',
        fine = 5000,
        months = 12,
        level = 'medium',
    },
    {
        id = 108,
        label = 'Cyber Extortion',
        description = 'Using digital means to extort money or valuables through threats.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 109,
        label = 'Digital Evidence Tampering',
        description = 'Altering, deleting, or manipulating digital evidence in investigation.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    {
        id = 110,
        label = 'Unauthorized Network Access',
        description = 'Illegally accessing computer networks or systems.',
        fine = 7500,
        months = 18,
        level = 'high',
    },
    -- Gang-Related Offenses
    {
        id = 111,
        label = 'Criminal Organization',
        description = 'Participating in organized criminal activities or gang operations.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 112,
        label = 'Gang Enhancement',
        description = 'Additional charge for committing crime to benefit criminal organization.',
        fine = 10000,
        months = 24,
        level = 'high',
    },
    -- Financial Crimes
    {
        id = 113,
        label = 'Money Laundering',
        description = 'Concealing origin of illegally obtained money through legitimate channels.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
    {
        id = 114,
        label = 'Tax Evasion',
        description = 'Intentional avoidance of tax payment through illegal means.',
        fine = 15000,
        months = 36,
        level = 'high',
    },
    {
        id = 115,
        label = 'Insider Trading',
        description = 'Trading stocks based on non-public material information.',
        fine = 20000,
        months = 48,
        level = 'high',
    },
}

