return {
    {
        id = 1,
        label = 'Speeding (Minor)',
        description = 'Exceeding the speed limit by up to 10 mph.',
        fine = 100,
        months = 0,
        level = 'low',
    },
    {
        id = 2,
        label = 'Speeding (Moderate)',
        description = 'Exceeding the speed limit by 11-20 mph.',
        fine = 500,
        months = 0,
        level = 'medium',
    },
    {
        id = 3,
        label = 'Speeding (Severe)',
        description = 'Exceeding the speed limit by over 20 mph.',
        fine = 1500,
        months = 1,
        level = 'high',
    },
    {
        id = 4,
        label = 'Reckless Driving',
        description = 'Operating a vehicle in a manner that endangers others.',
        fine = 3000,
        months = 3,
        level = 'high',
    },
    {
        id = 5,
        label = 'DUI (First Offense)',
        description = 'Driving under the influence of alcohol or drugs.',
        fine = 2000,
        months = 6,
        level = 'medium',
    },
    {
        id = 6,
        label = 'DUI (Repeat Offense)',
        description = 'Repeated offense of driving under the influence.',
        fine = 5000,
        months = 12,
        level = 'critical',
    },
    {
        id = 7,
        label = 'Assault (Minor)',
        description = 'Physical attack causing minor injuries.',
        fine = 1000,
        months = 6,
        level = 'low',
    },
    {
        id = 8,
        label = 'Assault (Severe)',
        description = 'Physical attack causing severe injuries.',
        fine = 5000,
        months = 24,
        level = 'high',
    },
    {
        id = 9,
        label = 'Robbery',
        description = 'Taking property from another person by force or threat.',
        fine = 10000,
        months = 36,
        level = 'critical',
    },
    {
        id = 10,
        label = 'Murder',
        description = 'Unlawful killing of another person.',
        fine = 25000,
        months = 60,
        level = 'critical',
    },
}
